# Creates a dictionary for site codes

site_reference <- dplyr::tibble(unit_code = c("D20N", "D20", "K32", "V47", "H09", "Z89", "C90", "Q13", "S28", "F42", "F54", "Q70", "Q70W", "R42"),
                         site_code = c(rep("RGT", 2),
                                       rep("GSTT??", 4),
                                       rep("RYJ", 2),
                                       rep("Oxford", 3),
                                       rep("UCL", 2),
                                       "Unknown"),
                         hospital  = c(rep("Addenbrooke\'s Hospital", 2),
                                       "Guy\'s Hospital",
                                       rep("St. Thomas\' Hospital", 3),
                                       "Hammersmith Hospital",
                                       "St. Mary\'s Hospital",
                                       "John Radcliffe",
                                       "Oxford Neuro",
                                       "Oxford Horton",
                                       "University College Hospital",
                                       "Westmoreland Street",
                                       "Unknown"),
                            type = rep("ICU", 14),
                           trust = c(rep("Cambridge", 2),
                                   rep("GSTT", 4),
                                   rep("Imperial", 2),
                                   rep("Oxford", 3),
                                   rep("UCLH", 2),
                                   "Unknown"))
